service: aws-lambda-puppeteer
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::aws-lambda-puppeteer-tutorial/*

layers:
  Chrome:
    path: layer
    description: Chrome Binary

functions:
  generate-pdf:
    handler: dist/handler.generatePDF
    layers:
      - { Ref: ChromeLambdaLayer }
    timeout: 300
